apiVersion: v1
kind: Secret
metadata:
  name: nestjs-auth-secrets
type: Opaque
stringData:
  DB_PASSWORD: "password"
  REDIS_PASSWORD: "password"
  JWT_SECRET: "my_secret_key"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nestjs-auth-config
data:
  DB_NAME: "nest-jwt-authentication"
  DB_USER: "root"
  PORT: "3306"